title: Self-Transcendence
email: natural-system@users.noreply.github.com
description: >-
  自豪的说，拥有一个高度健全+高度整合的人格，是非常幸运的事

# 核心修正：指定 GitHub Pages 的二级目录路径与域名
baseurl: "/self-transcendence"
url: "https://natural-system.github.io"

# 核心修正：禁用默认主题，完全使用本地自定义模板 (_layouts)
# theme: jekyll-theme-primer

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - blog-template.md

# 日志集合配置
collections:
  logs:
    output: true
    permalink: /api/logs/:name.json
