title: Self-Transcendence
email: natural-system@users.noreply.github.com
description: >-
  自豪的说，拥有一个高度健全+高度整合的人格，是非常幸运的事

# 核心修正：指定 GitHub Pages 的二级目录路径与域名
baseurl: "/self-transcendence"
url: "https://natural-system.github.io"

# 核心修正：禁用默认主题，完全使用本地自定义模板 (_layouts)
# theme: jekyll-theme-primer

plugins:
  - jekyll-feed
  - jekyll-seo-tag
# - jekyll-sitemap

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - blog-template.md

collections:
  logs:
    output: true
    permalink: /log/:name/

# 批量覆盖所有文章的 permalink 规则（顶格编写，与 collections 平级）
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /p/:year/:month/:day/:slugify/     
      #原来 ID 不可变容易导致同一天内发布多篇文章产生命名冲突。
      #permalink: /p/:year/:month/:day/:i_day/