title: Self-Transcendence
email: lb@zasv.com
description: >-
  自豪的说，我有一个高度健全+高度整合的人格。

# 核心修正：指定 GitHub Pages 的二级目录路径与域名
baseurl: "/self-transcendence"
url: "https://Natural-system.github.io"

# 核心修正：禁用 GitHub Pages 默认官方主题，允许加载自定义模板
theme: jekyll-theme-primer # 强制忽略
plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - blog-template.md
